#!/usr/bin/env node
"use strict";

/**
 * fixtures.test.js — pin known-good outputs from the Python reference
 * implementation (cryze's src/relay/rc5.py + gutes_frame.py).
 *
 * Every vector here was generated by running cryze's Python code against
 * the same inputs. If any of these start failing, the JS port has
 * drifted from the reference and downstream decoding will break.
 *
 * Run with:  node test/fixtures.test.js
 * Exits 0 on full match, 1 on any mismatch.
 *
 * To regenerate these vectors when the Python reference changes, see
 * the comment at the bottom of this file.
 */

const { RC5, derivePerFrameKey, idEncrypt, idDecrypt } = require("../../../src/gutes/lib/rc5");
const { giotHashString } = require("../../../src/gutes/lib/session-crypto");

let failures = 0;
const fail = (msg) => { console.log(`  ✗ ${msg}`); failures++; };
const pass = (msg) => console.log(`  ✓ ${msg}`);
const section = (name) => console.log(`\n--- ${name} ---`);

function hexEq(actual, expected, label) {
  const a = actual.toString("hex");
  if (a === expected) pass(`${label} = ${a}`);
  else fail(`${label}: expected ${expected}, got ${a}`);
}

// ---- RC5-8B fixtures ---------------------------------------------------

section("RC5-8B (block=8, rounds=6)");
const rc5_8_vectors = [
  { key: "0000000000000000", pt: "0000000000000000", ct: "6318ffc7df4e2d8c" },
  { key: "ffffffffffffffff", pt: "ffffffffffffffff", ct: "200a02105b84e22d" },
  { key: "0001020304050607", pt: "08090a0b0c0d0e0f", ct: "a54df38919c800c2" },
  { key: "77772e6777656c6c2e63630000000000", pt: "0102030405060708", ct: "293d1aa04c45433f" },
];
for (const v of rc5_8_vectors) {
  const rc5 = new RC5({ blockBytes: 8, rounds: 6 }).setKey(Buffer.from(v.key, "hex"));
  const ct = rc5.encryptBlock(Buffer.from(v.pt, "hex"));
  hexEq(ct, v.ct, `enc(key=${v.key.slice(0, 12)}..., pt=${v.pt})`);
  const back = rc5.decryptBlock(ct);
  hexEq(back, v.pt, `dec round-trips`);
}

// ---- RC5-16B fixtures --------------------------------------------------

section("RC5-16B (block=16, rounds=6)");
const rc5_16_vectors = [
  { key: "00000000000000000000000000000000", pt: "00000000000000000000000000000000", ct: "49f1098ef33e8a9e237def4f66ba91de" },
  { key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", pt: "5500ff0102030405060708090a0b0c0d", ct: "0eb2a5cc6e79e673b23fc394f1d6f00e" },
  { key: "0123456789abcdef0123456789abcdef", pt: "00112233445566778899aabbccddeeff", ct: "36a4f9292be927c78eccfbd68f363b04" },
];
for (const v of rc5_16_vectors) {
  const rc5 = new RC5({ blockBytes: 16, rounds: 6 }).setKey(Buffer.from(v.key, "hex"));
  const ct = rc5.encryptBlock(Buffer.from(v.pt, "hex"));
  hexEq(ct, v.ct, `enc(key=${v.key.slice(0, 12)}..., pt=${v.pt.slice(0, 12)}...)`);
  const back = rc5.decryptBlock(ct);
  hexEq(back, v.pt, `dec round-trips`);
}

// ---- ID encrypt fixtures -----------------------------------------------

section("idEncrypt (per-frame term_id wrapping)");
const id_vectors = [
  { termId: "0102030405060708", sq: 0x00000000, chk: 0x00000000, enc: "41e039db5324085b" },
  { termId: "ffffffffffffffff", sq: 0xcafebabe, chk: 0xdeadbeef, enc: "893270043e4f2bd4" },
  { termId: "0000000000000000", sq: 0x12345678, chk: 0x9abcdef0, enc: "2d088a7af2ba6d46" },
];
for (const v of id_vectors) {
  const term = Buffer.from(v.termId, "hex");
  const sq = Buffer.alloc(4); sq.writeUInt32LE(v.sq, 0);
  const chk = Buffer.alloc(4); chk.writeUInt32LE(v.chk, 0);
  const enc = idEncrypt(term, chk, sq);
  hexEq(enc, v.enc, `id_encrypt(${v.termId.slice(0, 8)}, sq=0x${v.sq.toString(16)}, chk=0x${v.chk.toString(16)})`);
  const back = idDecrypt(enc, chk, sq);
  hexEq(back, v.termId, `id_decrypt round-trips`);
}

// ---- Per-frame key derivation fixtures ---------------------------------

section("derivePerFrameKey (key derivation from frame header)");
const pfk_vectors = [
  { header: "390c8c7d7247342cd8100f2f6f770d65d670e58e0351d8ae", pfk: "390c8c7d0351d800" },
  { header: "8e4f6eac342fc231b7b08716eb3fc12896b9622317749428", pfk: "8e4f6eac17749400" },
  { header: "7733c28ee8ba53bdb56b8824577d53ecc28a70a61c7510a1", pfk: "7733c28e1c751000" },
];
for (const v of pfk_vectors) {
  const pfk = derivePerFrameKey(Buffer.from(v.header, "hex"));
  hexEq(pfk, v.pfk, `pfk(header=${v.header.slice(0, 12)}...)`);
}

// ---- giotHashString fixtures -------------------------------------------

section("giotHashString (session-key verification hash)");
const hash_vectors = [
  { input: "", expected: 0x4E67C6A7 },
  { input: "00", expected: 0xAEF5002E },
  { input: "0001020304050607", expected: 0x23C70B97 },
  { input: "68656c6c6f", expected: 0x6718EFCB }, // "hello"
];
for (const v of hash_vectors) {
  const data = Buffer.from(v.input, "hex");
  const h = giotHashString(data);
  const hHex = "0x" + h.toString(16).padStart(8, "0");
  const expectedHex = "0x" + v.expected.toString(16).padStart(8, "0");
  if (h === v.expected) pass(`giotHashString(${v.input || "empty"}) = ${hHex}`);
  else fail(`giotHashString(${v.input}): expected ${expectedHex}, got ${hHex}`);
}

// ---- Summary -----------------------------------------------------------

console.log();
if (failures === 0) {
  console.log("All fixture vectors match the Python reference.");
  process.exit(0);
} else {
  console.log(`${failures} mismatch(es). JS port has drifted — investigate before using.`);
  process.exit(1);
}

/*
 * REGENERATING THESE VECTORS
 * ==========================
 *
 * If the reference Python implementation in cryze changes (rare —
 * the protocol has been stable for years), run this script against
 * the latest cryze checkout to regenerate the expected values:
 *
 *   cd /path/to/cryze && python3 -c "
 *   import sys, struct
 *   sys.path.insert(0, 'src/relay')
 *   from rc5 import RC5, GWELL_KEY, derive_per_frame_key, id_encrypt, id_decrypt
 *
 *   for key_hex, pt_hex in [...]:  # see vectors above
 *       key = bytes.fromhex(key_hex)
 *       pt = bytes.fromhex(pt_hex)
 *       rc5 = RC5(block_bytes=8, rounds=6).setkey(key)
 *       ct = rc5.encrypt_block(pt)
 *       print(f'{{ key: \"{key_hex}\", pt: \"{pt_hex}\", ct: \"{ct.hex()}\" }},')
 *   "
 *
 * Paste the output into the vector arrays at the top of this file.
 */
