#!/usr/bin/env node
"use strict";

/**
 * fixtures.test.js — pin known-good outputs from docker-wyze-bridge's
 * Python reference. Every hex value here was generated by running
 * `app/wyzecam/tutk/tutk_protocol.encode()` against the same inputs.
 *
 * If any of these start failing, the JS port has drifted from the
 * reference and downstream camera communication will silently break.
 *
 * Run: node test/fixtures.test.js
 * Exit: 0 on full match, 1 on any mismatch.
 *
 * REGENERATING THESE VECTORS
 * --------------------------
 *
 *   pip install xxtea
 *   python3 -c "
 *   import sys, struct, json, xxtea
 *   def encode(code, data):
 *       data = data or b''
 *       return struct.pack(f'<BBHHH8x{len(data)}s', 72, 76, 5, code, len(data), data)
 *
 *   # K10042 night-vision auto:
 *   print(encode(10042, bytes([3])).hex())
 *   # K10092 set time=1700000000:
 *   print(encode(10092, struct.pack('<I', 1700000000)).hex())
 *   # ... etc
 *   "
 */

const { encode, decode } = require("../lib/codec");
const xxtea = require("../lib/xxtea");
const auth = require("../lib/auth");
const M = require("../lib/messages");

let failures = 0;
const fail = (m) => { console.log(`  ✗ ${m}`); failures++; };
const pass = (m) => console.log(`  ✓ ${m}`);
const section = (n) => console.log(`\n--- ${n} ---`);

function hexEq(actual, expected, label) {
  const a = actual.toString("hex");
  if (a === expected) pass(`${label}`);
  else fail(`${label}: expected ${expected}, got ${a}`);
}

// ---- K-class wire-byte fixtures ---------------------------------------

section("K-class encoded wire bytes (vs docker-wyze-bridge)");
const messageVectors = [
  {
    label: "K10000 (no body)",
    msg: new M.K10000ConnectRequest(null),
    hex: "484c0500102700000000000000000000",
  },
  {
    label: "K10000 with mac wake JSON",
    msg: new M.K10000ConnectRequest("AA:BB:CC:DD:EE:FF"),
    hex: "484c05001027450000000000000000007b2263616d657261496e666f223a7b226d6163223a2241413a42423a43433a44443a45453a4646222c22656e63466c6167223a302c2277616b657570466c6167223a317d7d",
  },
  {
    label: "K10042 night-vision auto",
    msg: new M.K10042SetNightVisionStatus(M.NV_AUTO),
    hex: "484c05003a270100000000000000000003",
  },
  {
    label: "K10092 set time=1700000000",
    msg: new M.K10092SetCameraTime(1700000000),
    hex: "484c05006c270400000000000000000000f15365",
  },
  {
    label: "K10052 bitrate=HD (0x78)",
    msg: new M.K10052SetBitrate(0x78),
    hex: "484c0500442706000000000000000000780000000000",
  },
  {
    label: "K10056 resolving 1080p/HD",
    msg: new M.K10056SetResolvingBit(0, 0x78),
    hex: "484c0500482703000000000000000000017800",
  },
  {
    label: "K10302 timezone=-5",
    msg: new M.K10302SetTimeZone(-5),
    hex: "484c05003e2801000000000000000000fb",
  },
  {
    label: "K11000 rotary (45,-30,5)",
    msg: new M.K11000SetRotaryByDegree(45, -30, 5),
    hex: "484c0500f82a050000000000000000002d00e2ff05",
  },
];

for (const v of messageVectors) {
  hexEq(v.msg.encode(), v.hex, v.label);
  // Every encoded message also has to round-trip through decode without throwing.
  try {
    const { header } = decode(v.msg.encode());
    if (header.code !== v.msg.code) fail(`${v.label} — decoded code mismatch`);
  } catch (e) {
    fail(`${v.label} — decode threw: ${e.message}`);
  }
}

// ---- XXTEA cross-language vectors -------------------------------------

section("XXTEA (vs pyxxtea — the package dwb uses)");
const xxteaVectors = [
  { label: "8B / ASCII-F key",
    pt: Buffer.from([0,1,2,3,4,5,6,7]),
    key: Buffer.from("FFFFFFFFFFFFFFFF", "ascii"),
    ct: "922fb3ed69e24564" },
  { label: "8B / 0xFF key",
    pt: Buffer.from([0,1,2,3,4,5,6,7]),
    key: Buffer.alloc(16, 0xFF),
    ct: "5d6960ca4f937bd3" },
  { label: "32B ASCII pt / ASCII-F key",
    pt: Buffer.from("0123456789abcdef0123456789abcdef", "ascii"),
    key: Buffer.from("FFFFFFFFFFFFFFFF", "ascii"),
    ct: "6f649d40c37b698e5548c1a47203342903ffa8e2db4f1ed20d656680c36122e0" },
];
for (const v of xxteaVectors) {
  hexEq(xxtea.encrypt(v.pt, v.key), v.ct, `enc ${v.label}`);
  const back = xxtea.decrypt(xxtea.encrypt(v.pt, v.key), v.key);
  if (back.equals(v.pt)) pass(`dec round-trips: ${v.label}`);
  else fail(`dec mismatch: ${v.label}`);
}

// ---- Auth challenge-response vectors ----------------------------------

section("generateChallengeResponse (status=3 standard path)");
{
  const enr = "EXAMPLEENR123456";
  const challenge = Buffer.alloc(16);
  for (let i = 0; i < 16; i++) challenge[i] = i;
  const resp = auth.generateChallengeResponse(challenge, enr, 3);
  hexEq(resp, "a273cf06a293adfe481dc1ed407fa70f",
    `enr="${enr}" challenge=0..15 status=3`);
}

// ---- Summary ----------------------------------------------------------

console.log();
if (failures === 0) {
  console.log("All Tutk fixture vectors match the docker-wyze-bridge / pyxxtea reference.");
  process.exit(0);
} else {
  console.log(`${failures} mismatch(es). JS port has drifted — investigate before using.`);
  process.exit(1);
}
